# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e17b1d2fd61031678eb0c4496b9d93d78373f5e513879589a11c3fb040d64b244122386c7ba490e87bcaff4f4d5cd15a089033426d8f05ea91fcf1b7d5d241d

test:
  secret_key_base: 0eca174d75a97656140129038d63e63a2d71c08eadde107714b9e1905c4611c7cc4e9c214ce946c0fd59fcba8359a08c0df3374614bc5431a7dff0dec9f74db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
